theme: minima
title: Subject to change
author: Felix Müller
email: felix-im-internet@yahoo.de
description: > # this means to ignore newlines until "baseurl:"
  This blog is about programming.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
